### ISSUE TITLE
Frodo RC1 error

### ISSUE THREAD

**Issue by chrstnwhlrt** [vially/googlemusic-xbmc#11]
Hi,
the script doesn't work with Frodo RC 1. Playing a song just shows the "error in addon" issue.
Last lines of the log:

22:56:52 T:139801629992704  NOTICE: Thread XBPyThread start, auto delete: false
22:56:52 T:139801629992704  NOTICE: -->Python Interpreter Initialized<--
22:56:52 T:139801629992704  NOTICE: GoogleMusic-0.2.1
22:56:53 T:139801629992704  NOTICE: CommonFunctions-1.4.0
22:56:54 T:139801629992704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "/home/christian/.xbmc/addons/plugin.audio.googlemusic/default.py", line 43, in <module>
                                                navigation.executeAction(params)
                                              File "/home/christian/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicNavigation.py", line 59, in executeAction
                                                self.playSong(params)
                                              File "/home/christian/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicNavigation.py", line 148, in playSong
                                                url = self.api.getSongStreamUrl(get("song_id"))
                                              File "/home/christian/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicApi.py", line 60, in getSongStreamUrl
                                                stream_url = self.gmusicapi.get_stream_url(song_id)
                                              File "/home/christian/.xbmc/addons/script.module.gmusicapi/lib/gmusicapi/api.py", line 371, in get_stream_url
                                                res = self._wc_call("play", query_args={'songid': song_id})
                                              File "/home/christian/.xbmc/addons/script.module.gmusicapi/lib/gmusicapi/api.py", line 624, in _wc_call
                                                res = json.loads(read)
                                              File "/usr/lib/python2.7/json/__init__.py", line 328, in loads
                                                return _default_decoder.decode(s)
                                              File "/usr/lib/python2.7/json/decoder.py", line 365, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "/usr/lib/python2.7/json/decoder.py", line 383, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
22:56:54 T:139803028227968   ERROR: Playlist Player: skipping unplayable item: 16, path [plugin://plugin.audio.googlemusic/?action=play_song&song_id=df58fd50-41ad-395c-8a84-476d857739b5]

**Comment by ghost** [comment]
Hmmm, I can't confirm this. Working fine on RC1 here, have you tried a different song? Try clearing your cache as well and re-attempting.

**Comment by chrstnwhlrt** [comment]
Ok clearing the cache fixed the issue! Thanks!
