### ISSUE TITLE
Playlist Error

### ISSUE THREAD

**Issue by cagnulein** [vially/googlemusic-xbmc#32]
Here the log:

11:32:30 T:2847437888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('id',)
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.xbmc/addons/plugin.audio.googlemusic/default.py", line 78, in <module>
                                                navigation.listMenu(params)
                                              File "/home/xbmc/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicNavigation.py", line 42, in listMenu
                                                listItems = self.getStationTracks(get('id'))
                                              File "/home/xbmc/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicNavigation.py", line 244, in getStationTracks
                                                url = '%s?action=play_song&song_id=%s&title=%s' % (sys.argv[0],track['id'].encode('utf8'),track['title'].encode('utf8'))
                                            KeyError: ('id',)
                                            -->End of Python script error report<--
11:32:31 T:3041513472   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic/?id=0f3a2913-4efd-3e0d-96a1-03fc4a2d84e9&path=station
11:32:31 T:3041513472   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic/?id=0f3a2913-4efd-3e0d-96a1-03fc4a2d84e9&path=station) failed

**Comment by foreverguest** [comment]
this should be fixed in develop now
