### ISSUE TITLE
simplejson not on OS X 10.9

### ISSUE THREAD

**Issue by tlm2021** [vially/googlemusic-xbmc#34]
It appears that the GoogleMusicPlaySong module is trying to import simplejson, but that module isn't available by default in OSX 10.6 (Python v2.7.5).

I'm running the latest monthly snapshot of XBMC from Dec. 01, 2013 (xbmc-13.0-Gotham_alpha10-x86_64.dmg). I'm also running version 0.8-exp14 that you posted to the thread about this plugin on the XBMC forums.

Here's this bit of log that encapsulates the error:

```
13:41:19 T:4588199936   DEBUG: StartScript - calling plugin Google Music Dev('plugin://plugin.audio.googlemusic/','1','')
13:41:19 T:4588199936   DEBUG: WaitOnScriptResult - waiting on the Google Music Dev (id=1) plugin...
13:41:19 T:4582170624  NOTICE: Thread LanguageInvoker start, auto delete: false
13:41:19 T:4582170624    INFO: initializing python engine.
13:41:19 T:4582170624   DEBUG: CPythonInvoker(1, /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/default.py): start processing
13:41:19 T:4582170624  NOTICE: -->Python Interpreter Initialized<--
13:41:19 T:4582170624   DEBUG: CPythonInvoker(1, /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/default.py): the source file to load is /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/default.py
13:41:19 T:4582170624   DEBUG: CPythonInvoker(1, /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/default.py): setting the Python path to /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic:/Users/travis/Library/Application Support/XBMC/addons/script.module.protobuf/lib:/Applications/XBMC.app/Contents/Resources/XBMC/addons/script.module.pil/lib:/Users/travis/Library/Application Support/XBMC/addons/script.module.gmusicapi/lib:/Users/travis/Library/Application Support/XBMC/addons/script.module.requests/lib:/Users/travis/Library/Application Support/XBMC/addons/script.module.decorator/lib:/Users/travis/Library/Application Support/XBMC/addons/script.module.mutagen/lib:/Applications/XBMC.app/Contents/Resources/XBMC/addons/xbmc.debug/:/Users/travis/Library/Application Support/XBMC/addons/script.module.parsedom/lib:/Users/travis/Library/Application Support/XBMC/addons/script.module.validictory/lib:/Applications/XBMC.app/Contents/Frameworks:/Applications/XBMC.app/Contents/Frameworks/lib/python26.zip:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/plat-darwin:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/plat-mac:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/plat-mac/lib-scriptpackages:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/lib-tk:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/lib-old:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/lib-dynload:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/site-packages:/Applications/XBMC.app/Contents/Frameworks/lib/python2.6/site-packages/PIL
13:41:19 T:4582170624   DEBUG: CPythonInvoker(1, /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/default.py): entering source directory /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic
13:41:19 T:4582170624   DEBUG: CPythonInvoker(1, /Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/default.py): instantiating addon using automatically obtained id of "plugin.audio.googlemusic" dependent on version 2.1.0 of the xbmc.python api
13:41:19 T:4582170624  NOTICE: GoogleMusic-0.8exp14 ARGV: ['plugin://plugin.audio.googlemusic/', '1', '']
13:41:19 T:4582170624   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named simplejson
                                            Traceback (most recent call last):
                                              File "/Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/default.py", line 43, in <module>
                                                import GoogleMusicPlaySong
                                              File "/Users/travis/Library/Application Support/XBMC/addons/plugin.audio.googlemusic/GoogleMusicPlaySong.py", line 2, in <module>
                                                import simplejson as json
                                            ImportError: No module named simplejson
                                            -->End of Python script error report<--
13:41:19 T:4582170624    INFO: Python script stopped
13:41:19 T:4582170624   DEBUG: Thread LanguageInvoker 4582170624 terminating
13:41:19 T:4588199936   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
```

_Edit_: Updated the log snippet with one that included the Python path.

**Comment by foreverguest** [comment]
this should be fixed in develop now
