### ISSUE TITLE
Python exception while loading (caching) library

### ISSUE THREAD

**Issue by bateast** [vially/googlemusic-xbmc#42]
On first start, an exception is triggered while fetching library.
Then, playlists are available, but empty, and no songs are presents in library.

hereafter the relevant part in xbmc.log
...
22:03:45 T:2789356608  NOTICE: [GoogleMusicEXP-1.1] Logging in
22:03:49 T:2789356608  NOTICE: [GoogleMusicEXP-1.1] Login succeeded
22:03:51 T:2789356608  NOTICE: [GoogleMusicEXP-1.1] [{xxxxxxxxxxxxx'}]
22:03:51 T:2789356608  NOTICE: [GoogleMusicEXP-1.1] Found device_id: yyyyyyyyyyyyy
22:03:51 T:2789356608  NOTICE: [GoogleMusicEXP-1.1] Loading library
22:03:51 T:2789356608  NOTICE: [GoogleMusicEXP-1.1] Loading auth from cache
22:06:04 T:2789356608  NOTICE: [GoogleMusicEXP-1.1] Library Size: 10518
22:06:11 T:2789356608   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('albumArtist',)
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.audio.googlemusic.exp/default.py", line 77, in <module>
                                                navigation.api.loadLibrary()
                                              File "/home/pi/.xbmc/addons/plugin.audio.googlemusic.exp/GoogleMusicApi.py", line 70, in loadLibrary
                                                self.storage.storeApiSongs(api_songs, 'all_songs')
                                              File "/home/pi/.xbmc/addons/plugin.audio.googlemusic.exp/GoogleMusicStorage.py", line 162, in storeApiSongs
                                                self.storeInAllSongs(api_songs)
                                              File "/home/pi/.xbmc/addons/plugin.audio.googlemusic.exp/GoogleMusicStorage.py", line 202, in storeInAllSongs
                                                ":url, :total_discs, :duration, :album_art_url, :display_name, NULL)", songs())
                                              File "/home/pi/.xbmc/addons/plugin.audio.googlemusic.exp/GoogleMusicStorage.py", line 182, in songs
                                                'album_artist':  api_song["albumArtist"] if api_song["albumArtist"] else api_song["artist"] if api_song["artist"] else '-Unknown-',
                                            KeyError: ('albumArtist',)
                                            -->End of Python script error report<--
22:06:12 T:3037500192   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
22:06:12 T:3037500192   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed
...

**Comment by foreverguest** [comment]
Please check if this version fix this error: https://app.box.com/s/xbsugoq2pe9qh7vc5ojm

**Comment by bateast** [comment]
It is working. Can be closed.

thank you very much.
