### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by svu** [vially/googlemusic-xbmc#45]
Tried to do "Play Album". Got this in the log:

23:42:18 T:139760634943232   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: getFilterSongs() takes exactly 4 arguments (3 given)
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.audio.googlemusic.exp/default.py", line 82, in <module>
                                                navigation.executeAction(params)
                                              File "/storage/.xbmc/addons/plugin.audio.googlemusic.exp/GoogleMusicNavigation.py", line 100, in executeAction
                                                self.playAll(params)
                                              File "/storage/.xbmc/addons/plugin.audio.googlemusic.exp/GoogleMusicNavigation.py", line 201, in playAll
                                                songs = self.api.getFilterSongs(get('filter_type'), get('filter_criteria'))
                                            TypeError: getFilterSongs() takes exactly 4 arguments (3 given)
                                            -->End of Python script error report<--

**Comment by foreverguest** [comment]
Bug confirmed, will fix soon, thanks.

**Comment by foreverguest** [comment]
Fixed, reopen if needed.
