### ISSUE TITLE
Invalid credentials / connection problem

### ISSUE THREAD

**Issue by gilcoh33** [vially/googlemusic-xbmc#66]
Hi

Someone was getting this error lately?
"Invalid credentials / connection problem"

I'm using "App passwords" - was fine for almost an year but the passed week I got connection errors
Did Google change something in their API?

**Comment by foreverguest** [comment]
Are you using my latest addon 1.4alpha4 https://app.box.com/s/0kraaris51qpac9qzv1iff7hnkehs6zp?

**Comment by gilcoh33** [comment]
Well it is working properly with your latest version yes, but lately I've been using the version when the album page is using the album tag and not the album artist tag, which created by @rui-castro

**Comment by rui-castro** [comment]
Hi @gilcoh33,

I'm having the same issue.
I will update the plugin as soon as I find the solution for the issue.

**Comment by gilcoh33** [comment]
Thanks @rui-castro ! 
All the best!

**Comment by rui-castro** [comment]
Hi @gilcoh33,
The issue is fixed in my fork and available in my repo http://kodi.ruicastro.me/ 
NOTE: I only tested with kodi 15 in ubuntu 14.04 64-bit.

**Comment by gilcoh33** [comment]
Amazing
Thanks man!

**Comment by Decipher** [comment]
@rui-castro Are you planning on making a PR for your fixed fork?

**Comment by rui-castro** [comment]
Hi @Decipher,

I don't know what PR means :) but I have a KODI repository with the plugin updated in http://kodi.ruicastro.me/.
The repository addon is here http://kodi.ruicastro.me/repository.ruicastro/repository.ruicastro-1.0.1.zip.

**Comment by Decipher** [comment]
A Pull Request.

When you fork a project to make a change, the polite thing to do is create
a Pull Request to give back to the original project.

I did try your fork and it didn't work either, but in a different way.
Haven't got times to dig into the code at the minute though.

## 

http://stuar.tc/lark
@Decipher

**Comment by rui-castro** [comment]
@Decipher I've made contributions to this repo before, with new features and bug fixes.

At the moment, [my fork](https://github.com/rui-castro/googlemusic-xbmc/tree/ruicastro) doesn't have any functional changes, just a different packaging.

I created KODI addons for dependencies I didn't find already in KODI repos - https://github.com/rui-castro?tab=repositories

This Google Music addon (with my packaging) and it's dependencies are all available in my repo http://kodi.ruicastro.me/.

**Comment by DunklerPhoenix** [comment]
Hi. 
I'm using version 1.8.3 with openelec and raspberrypi 2.
My Google Account is an Google Apps account with 2 factor authentication and custom domain (me@domain.com). I'm using an app specific password to login into the plugin, but I always get the error: invalid credentials / connection error. 
In the debug log is only "login failed"  written. 

Do you know how to fix this? I tried also to go to g.co/allowaccess over a ssh tunnel from another pc, but this didn't work either. 
Did Google change again something?

**Comment by foreverguest** [comment]
Was it working before?

**Comment by DunklerPhoenix** [comment]
Yes it worked. (a half year ago :P). Now I use my raspberry again and it doesn't work anymore. Unfortunately I can't get the server response from the request. Otherwise I could find, why it don't work.

**Comment by philBrown** [comment]
Version: 1.9.2
Platform: OpenELEC on a Raspberry Pi 2 (Model B)

I authorize the add-on with an app password due to 2FA and it was working fine up until yesterday (5th July, 2016). Tried creating a new password but the result is the same.

Here's the log entry when attempting to open the add-on

```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'gmusicapi.exceptions.CallFailure'>
    Error Contents: ListTracks: 401 Client Error: Unauthorized for url: https://mclients.googleapis.com/sj/v2.4/trackfeed?alt=json&updated-min=0&hl=en_US&include-tracks=true
    (requests kwargs: {'url': 'https://mclients.googleapis.com/sj/v2.4/trackfeed', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'data': '{}', 'method': 'POST', 'params': {'alt': 'json', 'updated-min': 0, 'hl': 'en_US', 'include-tracks': 'true'}})
    (response was: u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "authError",\n    "message": "Invalid Credentials",\n    "locationType": "header",\n    "location": "Authorization"\n   }\n  ],\n  "code": 401,\n  "message": "Invalid Credentials"\n }\n}\n')
    Traceback (most recent call last):
      File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 45, in <module>
        GoogleMusicApi.GoogleMusicApi().loadLibrary()
      File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicApi.py", line 63, in loadLibrary
        for chunk in gen:
      File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/clients/mobileclient.py", line 1180, in _get_all_items_incremental
        **kwargs)
      File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/clients/shared.py", line 81, in _make_call
        return protocol.perform(self.session, self.validate, *args, **kwargs)
      File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/protocol/shared.py", line 225, in perform
        raise CallFailure(err_msg, call_name)
    CallFailure: ListTracks: 401 Client Error: Unauthorized for url: https://mclients.googleapis.com/sj/v2.4/trackfeed?alt=json&updated-min=0&hl=en_US&include-tracks=true
    (requests kwargs: {'url': 'https://mclients.googleapis.com/sj/v2.4/trackfeed', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'data': '{}', 'method': 'POST', 'params': {'alt': 'json', 'updated-min': 0, 'hl': 'en_US', 'include-tracks': 'true'}})
    (response was: u'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "authError",\n    "message": "Invalid Credentials",\n    "locationType": "header",\n    "location": "Authorization"\n   }\n  ],\n  "code": 401,\n  "message": "Invalid Credentials"\n }\n}\n')
    -->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
```

**Comment by philBrown** [comment]
Removed `.kodi/userdata/addon_data/plugin.audio.googlemusic.exp/settings.xml` and re-configured and it's working again.

**Comment by svu** [comment]
I removed settings. Still cannot authenticate using the app passord (2-stage authentication):
20:38:32 T:139999332787968  NOTICE: -->Python Interpreter Initialized<--
20:38:32 T:139999332787968  NOTICE: [GoogleMusicEXP-1.10.5]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '6', ''] 
20:38:32 T:139999332787968  NOTICE: [GoogleMusicEXP-1.10.5] Checking init data  
20:40:36 T:139999492175616  NOTICE: Thread JobWorker start, auto delete: true
20:41:16 T:139999332787968  NOTICE: [GoogleMusicEXP-1.10.5] Initing addon data  
20:41:17 T:139999332787968  NOTICE: [GoogleMusicEXP-1.10.5] Trying to fetch the device_id  
20:41:17 T:139999332787968  NOTICE: [GoogleMusicEXP-1.10.5] Logging in  
20:41:17 T:139999332787968  NOTICE: [GoogleMusicEXP-1.10.5] Login in with device_id failed, trying with MAC
20:41:18 T:139999332787968  NOTICE: [GoogleMusicEXP-1.10.5] Login failed

**Comment by foreverguest** [comment]
I just have uploaded version 1.10.5 again with more debug strings.

Could you please download again and check for errors when logging in.

**Comment by svu** [comment]
As you can see, I pasted the log from 1.10.5. (kodi.log) Is there any other location of the log file to check?

**Comment by foreverguest** [comment]
Yes, but I uploaded a new 1.10.5, please uninstall, download and install.
https://app.box.com/s/r5mlbjt3t7la8yp655tduzzs5y3g4laj

**Comment by svu** [comment]
Uninstalled. Downloaded. Rebooted. Installed.
21:07:33 T:140192396588800  NOTICE: Previous line repeats 3 times.
21:07:33 T:140192396588800  NOTICE: Thread LanguageInvoker start, auto delete: false 
21:07:33 T:140192396588800  NOTICE: -->Python Interpreter Initialized<--  
21:07:33 T:140192396588800  NOTICE: [GoogleMusicEXP-1.10.5]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '1', '']  
21:07:33 T:140192396588800  NOTICE: [GoogleMusicEXP-1.10.5] Initing addon data
21:07:33 T:140192396588800  NOTICE: [GoogleMusicEXP-1.10.5] Trying to fetch the device_id
21:07:33 T:140192396588800  NOTICE: [GoogleMusicEXP-1.10.5] Logging in
21:07:34 T:140192396588800  NOTICE: [GoogleMusicEXP-1.10.5] Login in with device_id failed, trying with MAC
21:07:34 T:140192396588800  NOTICE: [GoogleMusicEXP-1.10.5] Login failed

**Comment by foreverguest** [comment]
Well, nothing changed...
I think the problem is related to not been able to retrieve your android device id, that should be registered in your account.
I have added new debug messages to detect error, but no error is printed.

If you access google page https://security.google.com/settings/security/activity, can you see your Android device there?

**Comment by svu** [comment]
No, I do not see that device. But ... wait, I am not on android, I am on openelec linux distro. Does that matter?

**Comment by foreverguest** [comment]
You must have at least one Android device in that list to be able to access Google api. Doesn't need to be the same you are using with OpenElec.

**Comment by svu** [comment]
I have one android device (Samsung S7), it is listed there. So what's next step?

**Comment by foreverguest** [comment]
If you have then it should be retrieved by the addon, and should be logged after the "trying to fetch the device_id"

**Comment by svu** [comment]
Apparently cannot...

**Comment by svu** [comment]
How can it get android device id before the logon? Just in case, I created new app password, specified GMEXP as the name - no change...

**Comment by svu** [comment]
I added some more logging, enabled logging in the gmusicapi:
OpenELEC:~/.kodi/addons/plugin.audio.googlemusic.exp # tail -f ../../temp/gmusicapi.log 
!-- begin debug log --!
version: 9.0.1-dev
logging to: /storage/.kodi/temp/gmusicapi.log
2016-10-27 00:34:56,070 - gmusicapi.Mobileclient1 (shared:71) [INFO]: initialized
2016-10-27 00:34:56,072 - gmusicapi.Mobileclient1 (shared:95) [INFO]: logged out
2016-10-27 00:34:56,832 - gmusicapi.Mobileclient1 (mobileclient:108) [INFO]: failed to authenticate
2016-10-27 00:34:57,444 - gmusicapi.Mobileclient1 (mobileclient:108) [INFO]: failed to authenticate

**Comment by svu** [comment]
And I checked login/password in the log - they are what google provided to me

**Comment by svu** [comment]
DO NOT LAUGH AT ME. I was using securesally@gmail.com literally :) Sorry for the trouble

**Comment by welshy1978** [comment]
Hi, having the "invalid login credentials error" on 1.11 but working fine on 1.10.6?  Using Amazon Fire Tv Box.  No problem for me using 1.10.6 but just thought i'd mention it ?

**Comment by foreverguest** [comment]
Thanks for your feedback. Check if version in link below fixes the problem:
https://app.box.com/s/w616z4lhwm06maej2fbe4cn9pi48szyj

**Comment by welshy1978** [comment]
Yes, that works, thank you.

**Comment by thepasto** [comment]
Hello, a couple of days ago i got the "invalid credentials or connectivity problems" on 1.11.1 version.
Here's the log
```
18:58:23.174 T:1589638032  NOTICE: [GoogleMusicEXP-1.11.1]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '17', '']
18:58:24.243 T:1589638032  NOTICE: [GoogleMusicEXP-1.11.1] Checking init data
18:58:25.366 T:1589638032  NOTICE: [GoogleMusicEXP-1.11.1] Trying to fetch the device_id
18:58:25.366 T:1589638032  NOTICE: [GoogleMusicEXP-1.11.1] Logging in
18:58:26.064 T:1589638032  NOTICE: [GoogleMusicEXP-1.11.1] Login in with device_id failed, trying with MAC
18:58:26.394 T:1589638032  NOTICE: [GoogleMusicEXP-1.11.1] Login failed
18:58:29.222 T:1589638032   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
                                                utils.checkInit()
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 113, in checkInit
                                                login.initDevice()
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 52, in initDevice
                                                self.login()
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 109, in login
                                                raise
                                            TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            -->End of Python script error report<--
18:58:29.617 T:1914513488   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
18:58:29.617 T:1914513488   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed
```
I hope it could help you.
Thanks!

**Comment by foreverguest** [comment]
Check if version in link below works for you:
https://app.box.com/s/m3wxz9rk9jnj123ohgeouu9kn8w3e2fa

**Comment by thepasto** [comment]
Nope.. Always the same:

```
22:44:13.627 T:1190683536  NOTICE: [GoogleMusicEXP-1.12beta1] Login failed
22:44:13.630 T:1647195024  NOTICE: [GoogleMusicEXP-1.12beta1]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '20', '']
22:44:14.379 T:1647195024  NOTICE: [GoogleMusicEXP-1.12beta1] Checking init data
22:44:56.788 T:1647195024  NOTICE: [GoogleMusicEXP-1.12beta1] Trying to fetch the device_id
22:44:56.788 T:1647195024  NOTICE: [GoogleMusicEXP-1.12beta1] Logging in
22:44:57.154 T:1647195024  NOTICE: [GoogleMusicEXP-1.12beta1] Login in with device_id failed, trying with MAC
22:44:57.466 T:1647195024  NOTICE: [GoogleMusicEXP-1.12beta1] Login failed
22:44:57.482 T:1647195024   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
                                                utils.checkInit()
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 113, in checkInit
                                                login.initDevice()
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 52, in initDevice
                                                self.login()
                                              File "/var/lib/kodi/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 112, in login
                                                raise
                                            TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            -->End of Python script error report<--
22:44:58.013 T:1914513488   ERROR: Previous line repeats 1 times.
22:44:58.013 T:1914513488   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
22:44:58.013 T:1914513488   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed
```

**Comment by nula666** [comment]
I have exactly the same issue - the plugin have been working fine for almost a year - but as of today I always get the "invalid credentials" error message. I have tried deleting all google music plugin data, reinstalled 5 different versions of it - no luck. Then I have noticed that I have to have android device in the google music authorized devices list - which I have recently removed. Therefore I have added the android device back - again no change. It would be great to find a fix for this bug - if you need any further information please let me know. My log is following:

```
22:46:14.823 T:1730409456  NOTICE: [GoogleMusicEXP-1.12beta1]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '5', '']
22:46:16.670 T:1730409456  NOTICE: [GoogleMusicEXP-1.12beta1] Checking init data
22:46:47.116 T:1730409456  NOTICE: [GoogleMusicEXP-1.12beta1] Trying to fetch the device_id
22:46:47.116 T:1730409456  NOTICE: [GoogleMusicEXP-1.12beta1] Logging in
22:46:47.702 T:1730409456  NOTICE: [GoogleMusicEXP-1.12beta1] Login in with device_id failed, trying with MAC
22:46:48.056 T:1730409456  NOTICE: [GoogleMusicEXP-1.12beta1] Login failed
22:46:49.883 T:1730409456   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
                                                utils.checkInit()
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 113, in checkInit
                                                login.initDevice()
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 52, in initDevice
                                                self.login()
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 112, in login
                                                raise
                                            TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            -->End of Python script error report<--
22:46:50.023 T:1958674432   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
22:46:50.023 T:1958674432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed
22:47:34.127 T:1958674432   ERROR: Control 55 in window 10502 has been asked to focus, but it can't
22:47:36.443 T:1589052400  NOTICE: [GoogleMusicEXP-1.12beta1]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '6', '']
22:47:38.090 T:1589052400  NOTICE: [GoogleMusicEXP-1.12beta1] Checking init data
22:47:38.093 T:1589052400  NOTICE: [GoogleMusicEXP-1.12beta1] Trying to fetch the device_id
22:47:38.093 T:1589052400  NOTICE: [GoogleMusicEXP-1.12beta1] Logging in
22:47:38.551 T:1589052400  NOTICE: [GoogleMusicEXP-1.12beta1] Login in with device_id failed, trying with MAC
22:47:38.867 T:1589052400  NOTICE: [GoogleMusicEXP-1.12beta1] Login failed
22:47:40.663 T:1589052400   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
                                                utils.checkInit()
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 113, in checkInit
                                                login.initDevice()
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 52, in initDevice
                                                self.login()
                                              File "/home/osmc/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 112, in login
                                                raise
                                            TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            -->End of Python script error report<--
22:47:40.834 T:1958674432   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
22:47:40.834 T:1958674432   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed
```

I'm using osmc on Pi3 with Kodi 17.4

**Comment by foreverguest** [comment]
Some user reported that enabling 2-factor-authentication and using an app specific password works.
It seems Google is forcing this path for authentication.

**Comment by thepasto** [comment]
Ok it seems to work, enabling two factor auth definetly solve the issue

**Comment by ihusky02** [comment]
I have  this problem too. I use kodi on port of SailfishOS, but after install this plug-in I have this error, but I use 2 step aut..

06:12:15 T:3775288144  NOTICE: [GoogleMusicEXP-1.11.1]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '1', '']
06:12:16 T:3775288144  NOTICE: [GoogleMusicEXP-1.11.1] Checking init data
06:12:16 T:3775288144  NOTICE: [GoogleMusicEXP-1.11.1] Trying to fetch the device_id
06:12:16 T:3775288144  NOTICE: [GoogleMusicEXP-1.11.1] Logging in
06:12:17 T:3775288144  NOTICE: [GoogleMusicEXP-1.11.1] Login in with device_id failed, trying with MAC
06:12:17 T:3775288144  NOTICE: [GoogleMusicEXP-1.11.1] Login failed
06:12:22 T:3775288144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            Traceback (most recent call last):
                                              File "/home/nemo/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
                                                utils.checkInit()
                                              File "/home/nemo/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 113, in checkInit
                                                login.initDevice()
                                              File "/home/nemo/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 52, in initDevice
                                                self.login()
                                              File "/home/nemo/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 109, in login
                                                raise
                                            TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            -->End of Python script error report<--
06:12:22 T:4063604736   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/

**Comment by ihusky02** [comment]
I have this error too, I use kodi with this plugin on port of SailfishOS (Xiaomi Mido)

**Comment by padok** [comment]
Login failing on Kodi 18.0-BETA3 (c2e1b31) using app password.

```12:26:17.771 T:140169875273472  NOTICE: [GoogleMusicEXP-1.11.1] Checking init data
12:26:17.772 T:140169875273472  NOTICE: [GoogleMusicEXP-1.11.1] Trying to fetch the device_id
12:26:17.772 T:140169875273472  NOTICE: [GoogleMusicEXP-1.11.1] Logging in
12:26:18.233 T:140169875273472  NOTICE: [GoogleMusicEXP-1.11.1] Login in with device_id failed, trying with MAC
12:26:18.643 T:140169875273472  NOTICE: [GoogleMusicEXP-1.11.1] Login failed
12:26:20.369 T:140169875273472   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            Traceback (most recent call last):
                                              File "/home/louis/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
                                                utils.checkInit()
                                              File "/home/louis/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 113, in checkInit
                                                login.initDevice()
                                              File "/home/louis/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 52, in initDevice
                                                self.login()
                                              File "/home/louis/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 109, in login
                                                raise
                                            TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
                                            -->End of Python script error report<--
12:26:20.497 T:140167952176896   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
12:26:20.502 T:140170319093632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed
```

**Comment by padok** [comment]
For all of you who still have problems with the login, try 
https://accounts.google.com/b/0/DisplayUnlockCaptcha
to log you in.
Has worked for me now in the end.

**Comment by fpfranco** [comment]
> For all of you who still have problems with the login, try
> https://accounts.google.com/b/0/DisplayUnlockCaptcha
> to log you in.
> Has worked for me now in the end.

This finally got me to log in.
There are still some errors that come up now and then

**Comment by foreverguest** [comment]
I'm working in a new version that should end login problems. Uses Oauth authentication.
If you want to test: 
https://app.box.com/s/15e06xespw438u5dy17dahtsyn3b03wm

Only works in Kodi 18

**Comment by fpfranco** [comment]
> I'm working in a new version that should end login problems. Uses Oauth authentication.
> If you want to test:
> https://app.box.com/s/15e06xespw438u5dy17dahtsyn3b03wm
> 
> Only works in Kodi 18

I'll give it a try

**Comment by NonaSuomy** [comment]
Hey foreverguest!
Tested this version you linked to above doesn't seem to be working for the unsubscription accounts?
Is there something more to do to get this working?

**Comment by foreverguest** [comment]
Hi, fixed some problems, please test: https://app.box.com/s/7whrlps3a8qy75kg08eb07a55svaf97u
