### ISSUE TITLE
Unplayable item

### ISSUE THREAD

**Issue by arbrandes** [vially/googlemusic-xbmc#81]
I'm getting errors trying to play any song.   This is on the latest Kodi (15.2), on Ubuntu 15.10.  The log tells me:

```
ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.audio.googlemusic.exp/?action=play_song&song_id=3f801cc1-a489-36c9-9a53-c767fca1299c&title=Bananarama - Cruel Summer&artist=Various Artists&albumart=/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/icon.png]
```

The full traceback is:

```
Error Type: <type 'exceptions.TypeError'>
Error Contents: initializer for ctype 'int(*)()' must be a pointer to same type, not cdata 'int(*)()'
Traceback (most recent call last):
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 13, in <module>
    GoogleMusicPlaySong.GoogleMusicPlaySong().play(params)
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicPlaySong.py", line 13, in play
    params = self.__getSongStreamUrl(song_id, params)
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicPlaySong.py", line 53, in __getSongStreamUrl
    params['url'] = self.api.getSongStreamUrl(song_id)
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicApi.py", line 68, in getSongStreamUrl
    stream_url = self.getLogin().getStreamUrl(song_id)
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicApi.py", line 26, in getLogin
    self.getApi()
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicApi.py", line 12, in getApi
    import GoogleMusicLogin
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 3, in <module>
    from gmusicapi import Mobileclient
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/__init__.py", line 4, in <module>
    from gmusicapi.clients import Mobileclient
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/clients/__init__.py", line 3, in <module>
    from gmusicapi.clients.mobileclient import Mobileclient
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/clients/mobileclient.py", line 7, in <module>
    from gmusicapi import session
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/session.py", line 8, in <module>
    import gpsoauth
  File "/home/tv/.kodi/addons/plugin.audio.googlemusic.exp/gpsoauth/__init__.py", line 1, in <module>
    import requests
  File "/home/tv/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/tv/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 53, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 42, in <module>
    class Binding(object):
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 59, in Binding
    status=_osrandom_rand_status)
TypeError: initializer for ctype 'int(*)()' must be a pointer to same type, not cdata 'int(*)()'
```

**Comment by foreverguest** [comment]
This seems to be some error in your local python libs (openssl) please try to update all related packages.
