### ISSUE TITLE
Unable to launch the plugin after update to 1.8

### ISSUE THREAD

**Issue by neolao** [vially/googlemusic-xbmc#87]
I am on OpenELEC. The plugin does not start.

**Comment by foreverguest** [comment]
Have you tried version 1.8.2? Several bugs were fixed. If it still fails please check kodi.log for errors.

**Comment by neolao** [comment]
Yes I tried version 1.8.2.

The error is: `Error Contents: No module named distutils`

The stack trace:

```
Traceback (most recent call last):
    File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 36, in <module>
        import GoogleMusicLogin
    File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicLogin.py", line 3, in <module>
        from gmusicapi import Mobileclient
    File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/__init__.py", line 4, in <module>
        from gmusicapi.clients import Mobileclient
    File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/clients/__init__.py", line 3, in <module>
        from gmusicapi.clients.mobileclient import Mobileclient
    File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/clients/mobileclient.py", line 7, in <module>
        from gmusicapi import session
    File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/session.py",line 18, in <module>
        from gmusicapi.utils import utils
    File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/gmusicapi/utils/utils.py", line 7, in <module>
        from distutils import spawn
ImportError: No module named distutils
```

**Comment by foreverguest** [comment]
Check if version below works for you:
https://app.box.com/s/6yzdyflabwebtcdfrslp3csf4qy1hzwc

**Comment by neolao** [comment]
@foreverguest It works! Thank you very much
