### ISSUE TITLE
unknown addon id? Testing current branch.

### ISSUE THREAD

**Issue by kronflux** [vially/googlemusic-xbmc#90]
Just testing current branch, didn't modify anything, but I did manually add gmusicapi and gpsoauth.
I assume it's not release ready yet, but just thought I'd chime in, hoping this helps out :)

15:05:41 T:2744   ERROR: EXCEPTION: Unknown addon id 'plugin.audio.googlemusic.exp'.
15:05:41 T:2744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.RuntimeError'>
  Error Contents: Unknown addon id 'plugin.audio.googlemusic.exp'.
  Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Kodi\addons\plugin.audio.googlemusic.exp\default.py", line 1, in <module>
  import sys, utils, xbmc
  File "C:\Users\Owner\AppData\Roaming\Kodi\addons\plugin.audio.googlemusic.exp\utils.py", line 5, in <module>
  addon = xbmcaddon.Addon(id='plugin.audio.googlemusic.exp')
  RuntimeError: Unknown addon id 'plugin.audio.googlemusic.exp'.
  -->End of Python script error report<--
  15:05:41 T:3876   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.googlemusic/
  15:05:41 T:3876   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic/) failed

**Comment by foreverguest** [comment]
addon.xml file was pointing for old id, should be fixed now.

**Comment by kronflux** [comment]
It did fix that part, now here's what it gives :)

18:12:52 T:8040  NOTICE: [GoogleMusicEXP-0.8.2]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '1', '']
18:12:52 T:8040   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
  Error Type: <type 'exceptions.ImportError'>
  Error Contents: No module named future
  Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Roaming\Kodi\addons\plugin.audio.googlemusic.exp\default.py", line 22, in <module>
    import GoogleMusicLogin
  File "C:\Users\Owner\AppData\Roaming\Kodi\addons\plugin.audio.googlemusic.exp\GoogleMusicLogin.py", line 3, in <module>
    from gmusicapi import Mobileclient
  File "C:\Users\Owner\AppData\Roaming\Kodi\addons\plugin.audio.googlemusic.exp\gmusicapi__init__.py", line 4, in <module>
    from gmusicapi.clients import Webclient, Musicmanager, Mobileclient
  File "C:\Users\Owner\AppData\Roaming\Kodi\addons\plugin.audio.googlemusic.exp\gmusicapi\clients__init__.py", line 2, in <module>
    from gmusicapi.clients.webclient import Webclient
  File "C:\Users\Owner\AppData\Roaming\Kodi\addons\plugin.audio.googlemusic.exp\gmusicapi\clients\webclient.py", line 3, in <module>
    from future import standard_library
  ImportError: No module named future
  -->End of Python script error report<--
  18:12:52 T:7208   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
  18:12:52 T:7208   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed

**Comment by foreverguest** [comment]
This is part of gmusicapi dependencies, the "future" module.
Please check the list of requirements if you want to use the unmodified gmusicapi module https://github.com/simon-weber/gmusicapi/blob/develop/requirements.txt
