### ISSUE TITLE
Google Music Fails to start

### ISSUE THREAD

**Issue by gz** [vially/googlemusic-xbmc#93]
I installed Google Music for the first time and it failed to start with this error in the logs:

```
08:46:22 T:140071885854464  NOTICE: [GoogleMusicEXP-1.10.4]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '1', '']
08:46:23 T:140071885854464  NOTICE: [GoogleMusicEXP-1.10.4] Checking init data
08:46:23 T:140071885854464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: could not convert string to float: 
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 21, in <module>
                                                utils.checkInit()
                                              File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/utils.py", line 102, in checkInit
                                                storage.checkDbInit()
                                              File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicStorage.py", line 14, in checkDbInit
                                                difftime = time.time() - float(utils.addon.getSetting('fetched_all_songs'))
                                            ValueError: could not convert string to float: 
                                            -->End of Python script error report<--
08:46:23 T:140073615526016   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic.exp/
08:46:23 T:140073615526016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic.exp/) failed
```

As a workaround: It started working after I renamed the database file from googlemusic.db to googlemusic2.db in the App settings.

**Comment by foreverguest** [comment]
Thanks for reporting, I'll prepare a fix for next version.

**Comment by foreverguest** [comment]
Please test version below:
https://app.box.com/s/rleiunrlyn77wgawv3rutfja78x5k9lp

**Comment by omprakashmannan** [comment]
great sir
